### ISSUE TITLE
Handle all error exception from Okta server 

### ISSUE THREAD

**Issue by clarkshu1016** [okta/okta-mobile-kotlin#204]
### Describe the feature request.

There is a full error list for the okta provider
will native SDK will support handle all the exceptions in the future? 
https://developer.okta.com/docs/reference/error-codes/

there are two main steps in  standard ODIC protocol, 
1. get the authorization code step, Is there a full error list on the first step?
2. get the access token and idtoken. Is there a full error list on the second step?

### New or Affected Resource(s)

https://developer.okta.com/docs/reference/error-codes/

**Comment by JayNewstrom** [comment]
Hi @clarkshu1016 could you explain more about your use case? The SDK will handle all errors, or pass them along. Do you have specific errors you're interested in?

Does [this](https://okta.github.io/okta-mobile-kotlin/auth-foundation/com.okta.authfoundation.client/-oidc-client-result/-error/-http-response-exception/index.html) have the information you need?

**Comment by clarkshu1016** [comment]
Hi @JayNewstrom ,I may not understand well, recently the repository added cache well-known/openid-configuration results, but for the first time still need to request result, what if  network timeout, what if  discovery document parsing error ,what if  discovery specified mandatory field is missing. Did sdk handle this part of exception?

**Comment by JayNewstrom** [comment]
If the discovery document isn't available (for any of the reasons you mentioned) https://okta.github.io/okta-mobile-kotlin/auth-foundation/com.okta.authfoundation.client/-oidc-client-result/-error/-oidc-endpoints-not-available-exception/index.html will be returned in the error result. 

Errors are not cached. So the next time it's requested, it'll be requested over the network.

**Comment by clarkshu1016** [comment]
thanks, @JayNewstrom 's reply, another question is about authorization code flow when SDK gets authorization code from 302 redirections http://localhost?code=qaAdshksdaAdshh&state,  Is there a default authorization code expiration time? like 2 minutes or 1 minute, if it has a default value. if the authorization code value is expired, what error should return on SDK?

**Comment by JayNewstrom** [comment]
Can I ask your reasoning for wanting to use that error specifically? I think the default time is 1 minute, but I'm not sure.

**Comment by JayNewstrom** [comment]
The server returns a 400 with a body having 

```
{
	"error": "invalid_grant",
	"error_description": "The authorization code is invalid or has expired."
}
```

Which results in an `HttpResponseException`

```
    com.okta.authfoundation.client.OidcClientResult$Error$HttpResponseException: The authorization code is invalid or has expired.
        at com.okta.authfoundation.client.internal.NetworkUtilsKt.toOidcClientResultError(NetworkUtils.kt:137)
        at com.okta.authfoundation.client.internal.NetworkUtilsKt.access$toOidcClientResultError(NetworkUtils.kt:1)
        at com.okta.authfoundation.client.internal.NetworkUtilsKt$internalPerformRequest$5.invokeSuspend(NetworkUtils.kt:111)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

It looks like the timeout is 5 minutes.

**Comment by clarkshu1016** [comment]
@JayNewstrom thanks for explanation, helps me more understand the design of sdk
