### ISSUE TITLE
Application Stuck on 

### ISSUE THREAD

**Issue by rajeshjadidminc** [okta/okta-mobile-kotlin#224]
### Describe the bug?

I have tried with Browser flow and its working fine, the same credential I have tried with resource owner flow but it's not working and giving the below error:
also i have provide the grant type as well in okta dev portal 

`com.okta.authfoundation.client.OidcClientResult$Error$HttpResponseException: The client is not authorized to use the provided grant type. Configured grant types: [refresh_token, authorization_code].
                                                                                                    	at com.okta.authfoundation.client.internal.NetworkUtilsKt.toOidcClientResultError(NetworkUtils.kt:183)
                                                                                                    	at com.okta.authfoundation.client.internal.NetworkUtilsKt.access$toOidcClientResultError(NetworkUtils.kt:1)
                                                                                                    	at com.okta.authfoundation.client.internal.NetworkUtilsKt$internalPerformRequest$5.invokeSuspend(NetworkUtils.kt:116)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)`

,

### What is expected to happen?

The application should work as expected like browser flow.

### What is the actual behaviour?

block and giving error

### Reproduction Steps?

first, try with the browser and then try  with the resource owner 

### SDK Version and Artifact(s) used.

SDK 30

**Comment by JayNewstrom** [comment]
Hi @rajeshjadidminc,

You need to enable resource owner flow for your application. In the Okta Admin dashboard, navigate to Applications -> Applications, then select your application. Under general settings, you can enable the grant type.

<img width="741" alt="Screen Shot 2022-10-03 at 9 42 02 AM" src="https://user-images.githubusercontent.com/713288/193605917-5c1004df-a597-4240-b648-e05fe68e056f.png">

**Comment by JayNewstrom** [comment]
@rajeshjadidminc if you have any further issues or questions, please let us know!
