### ISSUE TITLE
App crashes after redirecting from web sign-in

### ISSUE THREAD

**Issue by jiaqi-transcarent** [okta/okta-mobile-kotlin#268]
### Describe the bug?

On some android devices, we discovered that app crashes right after user completes the sign-in on okta and gets redirected back to the app. So far we have only reproduced this on some devices with Android 13, still have no idea of what triggers the crash, here is the log:

```
Fatal Exception: java.lang.AbstractMethodError: abstract method "java.lang.Object java.lang.ClassValue.computeValue(java.lang.Class)"
       at java.lang.ClassValue.getFromHashMap(ClassValue.java:230)
       at java.lang.ClassValue.getFromBackup(ClassValue.java:212)
       at java.lang.ClassValue.get(ClassValue.java:116)
       at kotlinx.serialization.internal.ClassValueReferences.getOrSet(ClassValueReferences.java:77)
       at kotlinx.serialization.internal.ClassValueCache.get(Caching.kt:49)
       at kotlinx.serialization.SerializersCacheKt.findCachedSerializer(SerializersCache.kt:53)
       at kotlinx.serialization.SerializersKt__SerializersKt.serializerByKTypeImpl$SerializersKt__SerializersKt(Serializers.kt:141)
       at kotlinx.serialization.SerializersKt__SerializersKt.serializer(Serializers.kt:108)
       at kotlinx.serialization.SerializersKt.serializer(Serializers.kt:1)
       at com.okta.authfoundation.jwt.JwtParser$parse$2.invokeSuspend(JwtParser.kt:83)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

seems like something is wrong inside `com.okta.authfoundation.jwt.JwtParser`

update: it seems to be related to this one: https://stackoverflow.com/questions/76703935/what-is-the-potential-issue-with-proguard-and-classvalue-on-android-14

### What is expected to happen?

User gets redirected back to app with no issue.

### What is the actual behavior?

User gets redirected back to app, then the app crashes.

### Reproduction Steps?

```kotlin
    private fun signInViaWeb(userName: String) {
        mainScope.launch {
            // Setting credentials to store the okta accessToken
            webSsoCredentials = CredentialBootstrap.defaultCredential()

            // RedirectUrl determines where we will navigate the user to when the web sign in flow
            // is finished
            val redirectUrl: String = BuildConfig.OKTA_REDIRECT_URI

            // Initializing web sign in client
            webSignInClient =
                CredentialBootstrap.oidcClient.createWebAuthenticationClient()

            if (::activity.isInitialized) {
                // Using web client to login the user. The function will open a web page where user
                // can login using Okta widget.
                when (val result =
                    webSignInClient?.login(
                        activity,
                        redirectUrl,
                        mapOf("login_hint" to userName)
                    )) {
                    is OidcClientResult.Error -> {
                        Timber.e("Okta web login error.")
                    }

                    is OidcClientResult.Success -> {
                        // Saving the token for later use
                        webSsoCredentials?.storeToken(token = result.result)
                        webSignInAccessToken = result.result.accessToken
                        hasUserSuccessfullySignedIn = true
                        attemptedBiometricChallengeCancelled = false

                        // Passing the token to the app
                        streamHandler.send(webSignInAccessToken)
                    }

                    else -> {
                        Timber.e("Could not initialize sign in client")
                    }
                }
            }
        }
    }
```

### SDK Version and Artifact(s) used.

build.gradle:
```
group 'com.flutter.okta.okta'
version '1.0-SNAPSHOT'

buildscript {
    ext.kotlin_version = '1.7.21'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.2.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply from: project(':flutter_config').projectDir.getPath() + "/dotenv.gradle"

android {
    compileSdkVersion 33

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }
    defaultConfig {
        minSdkVersion 24
        manifestPlaceholders = [
                "appAuthRedirectScheme"          : "{customUriScheme}",
                "webAuthenticationRedirectScheme": "{redirectUriScheme}"
        ]
        buildConfigField "String", "OKTA_URL", "\"" + project.env.get("OKTA_URL") + "\""
        buildConfigField "String", "OKTA_CLIENT_ID", "\"" + project.env.get("OKTA_CLIENT_ID") + "\""
        buildConfigField "String", "OKTA_REDIRECT_URI", "\"" + project.env.get("OKTA_REDIRECT_URI") + "\""
        buildConfigField "String", "OKTA_ORG_URL", "\"" + project.env.get("OKTA_ORG_URL") + "\""
    }
    lintOptions {
        disable 'InvalidPackage'
    }
    compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }

    kotlinOptions {
        jvmTarget = "1.8"
    }
}

dependencies {
    implementation 'com.jakewharton.timber:timber:5.0.1'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.fragment:fragment-ktx:1.5.7'
    implementation 'com.okta.android:okta-oidc-android:1.3.4'
    implementation 'com.okta.authn.sdk:okta-authn-sdk-api:2.0.11'
    implementation('com.okta.authn.sdk:okta-authn-sdk-impl:2.0.11') {
        exclude group: 'com.okta.sdk', module: 'okta-sdk-httpclient'
    }
    implementation('com.okta.kotlin:auth-foundation')
    implementation('com.okta.kotlin:auth-foundation-bootstrap')
    implementation('com.okta.kotlin:oauth2')
    implementation('com.okta.kotlin:web-authentication-ui')
    implementation(platform('com.okta.kotlin:bom:1.1.5'))

    implementation 'com.okta.sdk:okta-sdk-okhttp:8.2.5'
    implementation 'androidx.preference:preference-ktx:1.2.0'
    // WARNING: When updating android dependencies you MUST run either a stage build in CI or do
    // Build>Generate Signed Bundle / APK and generate an APK with our .jks.
    implementation 'androidx.core:core-ktx:1.9.0'
}

```

gradle.properties:
```
org.gradle.jvmargs=-Xmx1536M
android.useAndroidX=true
android.enableJetifier=true
```

**Comment by rajdeepnanua-okta** [comment]
Hi @jiaqi-transcarent, thanks for reporting this issue, and for linking the relevant stackoverflow thread! I appreciate it 😄. I will update the compile SDK from 33 to 34, and kotlinx-serialization version, which as I understand it, should fix this issue. I'll update this thread once I've released the fix.

**Comment by rajdeepnanua-okta** [comment]
@jiaqi-transcarent, the release with the fix will be available by tomorrow EOD

**Comment by jiaqi-transcarent** [comment]
I'm closing this one as the issue has been solved, thx for your help! @rajdeepnanua-okta
