### ISSUE TITLE
App Crashing - Fatal Exception: java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: com.google.crypto.tink.shaded.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).

### ISSUE THREAD

**Issue by ABr751** [okta/okta-mobile-kotlin#273]
### Describe the bug?

Adding the logs for reference 

Fatal Exception: java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: com.google.crypto.tink.shaded.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
       at android.app.ActivityThread.installProvider(ActivityThread.java:8463)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:7963)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7649)
       at android.app.ActivityThread.-$$Nest$mhandleBindApplication()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2478)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8893)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
       
       
       Caused by androidx.startup.StartupException: com.google.crypto.tink.shaded.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
       at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:187)
       at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:238)
       at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206)
       at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2690)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2660)
       at android.app.ActivityThread.installProvider(ActivityThread.java:8458)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:7963)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7649)
       at android.app.ActivityThread.-$$Nest$mhandleBindApplication()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2478)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8893)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
       
       
       Caused by com.google.crypto.tink.shaded.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
       at com.google.crypto.tink.shaded.protobuf.GeneratedMessageLite.parsePartialFrom(GeneratedMessageLite.java:1566)
       at com.google.crypto.tink.shaded.protobuf.GeneratedMessageLite.parseFrom(GeneratedMessageLite.java:1663)
       at com.google.crypto.tink.proto.Keyset.parseFrom(Keyset.java:957)
       at com.google.crypto.tink.integration.android.SharedPrefKeysetReader.read(SharedPrefKeysetReader.java:84)
       at com.google.crypto.tink.CleartextKeysetHandle.read(CleartextKeysetHandle.java:58)
       at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.read(AndroidKeysetManager.java:328)
       at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readOrGenerateNewKeyset(AndroidKeysetManager.java:287)
       at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build(AndroidKeysetManager.java:238)
       at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:123)
       at com.okta.authfoundation.client.DeviceTokenProvider.<init>(DeviceTokenProvider.kt:47)
       at com.okta.authfoundation.client.DeviceTokenProvider.<init>(DeviceTokenProvider.kt)
       at com.okta.authfoundation.client.DeviceTokenProvider$Companion.initialize$auth_foundation_release(DeviceTokenProvider.kt:38)
       at com.okta.authfoundation.client.DeviceTokenInitializer.create(DeviceTokenInitializer.kt:23)
       at com.okta.authfoundation.client.DeviceTokenInitializer.create(DeviceTokenInitializer.kt:21)
       at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:180)
       at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:238)
       at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206)
       at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2690)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2660)
       at android.app.ActivityThread.installProvider(ActivityThread.java:8458)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:7963)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7649)
       at android.app.ActivityThread.-$$Nest$mhandleBindApplication()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2478)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8893)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

### What is expected to happen?

App should not crash

### What is the actual behavior?

App is  crashing 

### Reproduction Steps?

It's not a always-happening issue, it happens sometimes, but often.
Its not crashing when it was running in emulator but in real devices its crashing

### Additional Information?

Initialising it in Application class
 ```
    val oidcConfiguration = OidcConfiguration(
            clientId = BuildConfig.CLIENT_ID,
            defaultScope = BuildConfig.SCOPES.joinToString(" "),
        )
        val client = OidcClient.createFromDiscoveryUrl(
            oidcConfiguration,
            ("${BuildConfig.ISSUER}/.well-known/openid-configuration").toHttpUrl(),
        )
        CredentialBootstrap.initialize(client.createCredentialDataSource(this))
```

How can we fix this? Is it possible to  give a detailed explanation if you are suggesting a work around for the time being

### SDK Version and Artifact(s) used.

    implementation(platform('com.okta.kotlin:bom:1.1.5'))
    implementation('com.okta.kotlin:auth-foundation')
    implementation('com.okta.kotlin:auth-foundation-bootstrap')
    implementation('com.okta.kotlin:oauth2')
    implementation('com.okta.kotlin:web-authentication-ui')

**Comment by rangaprakash-okta** [comment]
Interim Fix Discussed here #270

**Comment by rajdeepnanua-okta** [comment]
This issue should be fixed in the recently released version 1.2.1 of the sdk
