### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException: : Unable to get provider androidx.startup.InitializationProvider: androidx.fragment.app.t: java.security.GeneralSecurityException: Keystore operation failed

### ISSUE THREAD

**Issue by slaldmi** [okta/okta-mobile-kotlin#277]
### Describe the bug?

Fatal Exception: java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.fragment.app.t: java.security.GeneralSecurityException: Keystore operation failed
       at android.app.ActivityThread.installProvider(ActivityThread.java:7247)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:6783)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6700)
       at android.app.ActivityThread.access$1300(ActivityThread.java:237)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7660)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

### What is expected to happen?

Fatal Exception: java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.fragment.app.t: java.security.GeneralSecurityException: Keystore operation failed
       at android.app.ActivityThread.installProvider(ActivityThread.java:7247)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:6783)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6700)
       at android.app.ActivityThread.access$1300(ActivityThread.java:237)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7660)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

### What is the actual behavior?

App crashing

Brand:Tinno - FIH Foxconn
Model:M10
Version:Android 11
Orientation:Portrait

### Reproduction Steps?

Fatal Exception: java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.fragment.app.t: java.security.GeneralSecurityException: Keystore operation failed
       at android.app.ActivityThread.installProvider(ActivityThread.java:7247)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:6783)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6700)
       at android.app.ActivityThread.access$1300(ActivityThread.java:237)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7660)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

### SDK Version and Artifact(s) used.

   okta-bom = "1.1.3"

    coreLibraryDesugaring libs.desugar.jdk.libs
    implementation(platform(libs.okta.bom))
    implementation('com.okta.kotlin:auth-foundation-bootstrap')
    implementation('com.okta.kotlin:web-authentication-ui')
    implementation libs.androidx.security.crypto.ktx
    implementation libs.androidx.security.crypto
    implementation libs.kotlinx.serialization.json
    implementation libs.androidx.biometric

### Build Information

androidGradlePlugin = "8.1.1"
org-jetbrains-kotlin-android = "1.8.10"
compose-bom = "2023.10.01"
biometric = "1.1.0"
security_crypto = "1.0.0"

**Comment by FeiChen-okta** [comment]
Fixed in v2.0.0
