### ISSUE TITLE
Crash when initialising through android start up

### ISSUE THREAD

**Issue by mpierucci** [okta/okta-mobile-kotlin#279]
### Describe the bug?

Initialising Okta's `CredentialBootstrap` client through [Androidx Startup library](https://developer.android.com/topic/libraries/app-startup) causes the application to crash often.

### What is expected to happen?

I'd expect not to crash and to be able to initialise the sdk through the library

### What is the actual behavior?

Crash with the following stack trace:

```
 Process: com.mpierucci.android.oktastartupissue, PID: 6942
                                                                                                    java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: kotlin.UninitializedPropertyAccessException: lateinit property instance has not been initialized
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:7841)
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7347)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7042)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2261)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8248)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
                                                                                                    Caused by: androidx.startup.StartupException: kotlin.UninitializedPropertyAccessException: lateinit property instance has not been initialized
                                                                                                    	at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:187)
                                                                                                    	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:238)
                                                                                                    	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206)
                                                                                                    	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45)
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2619)
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2589)
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:7836)
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7347) 
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7042) 
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2261) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205) 
                                                                                                    	at android.os.Looper.loop(Looper.java:294) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8248) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971) 
                                                                                                    Caused by: kotlin.UninitializedPropertyAccessException: lateinit property instance has not been initialized
                                                                                                    	at com.okta.authfoundation.client.DeviceTokenProvider$Companion.getDeviceToken$auth_foundation_release(DeviceTokenProvider.kt:33)
                                                                                                    	at com.okta.authfoundation.client.DeviceTokenCookieJar.<init>(DeviceTokenCookieJar.kt:28)
                                                                                                    	at com.okta.authfoundation.AuthFoundationDefaults$cookieJar$2.invoke(AuthFoundationDefaults.kt:75)
                                                                                                    	at com.okta.authfoundation.AuthFoundationDefaults$cookieJar$2.invoke(AuthFoundationDefaults.kt:75)
                                                                                                    	at com.okta.authfoundation.NoSetAfterGetWithLazyDefaultFactory.getValue(NoSetAfterGetWithLazyDefaultFactory.kt:30)
                                                                                                    	at com.okta.authfoundation.AuthFoundationDefaults.getCookieJar(AuthFoundationDefaults.kt:75)
                                                                                                    	at com.okta.authfoundation.client.OidcConfiguration.<init>(OidcConfiguration.kt:98)
                                                                                                    	at com.mpierucci.android.oktastartupissue.OktaInitializer.create(OktaInitializer.kt:16)
                                                                                                    	at com.mpierucci.android.oktastartupissue.OktaInitializer.create(OktaInitializer.kt:13)
                                                                                                    	at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:180)
                                                                                                    	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:238) 
                                                                                                    	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206) 
                                                                                                    	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45) 
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2619) 
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2589) 
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:7836) 
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7347) 
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7042) 
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2261) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205) 
                                                                                                    	at android.os.Looper.loop(Looper.java:294) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8248) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971) 
```

### Reproduction Steps?

Simply add the init code provided by the repo's github inside a startup initialiser instead of on the base app ( as suggested in the docs)
[Here is a minimal repo configured](https://github.com/mpierucci/OktaSdkStartupIusse) already, simply run the app a few times and you'll see the crash on the logcat.

### SDK Version and Artifact(s) used.

BOM 1.2.0
Foundation Bootstrap

**Comment by rajdeepnanua-okta** [comment]
I released a fix for this issue with the freshly released version 1.2.1
